version: '3'
services:
  tweb:
    image: "gcr.io/$PROJECT_ID/taxeedee_html:working"
    ports:
     - "5000:5000"
    depends_on:
      - server
  mongo:
    image: "mongo"
    volumes:
      - "~/tmp/dockerdata:/data/db"
  mongo-express:
    image: "mongo-express"
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
    depends_on:
        - mongo
  server:
    image: "gcr.io/$PROJECT_ID/taxeedee_db:working"
    ports:
     - "50051:50051"
    depends_on:
      - mongo
