version: '3'



services:
    mongo:
        image: mongo
        ports:
            - "27019:27017"
    mongo-express:
        image: mongo-express
        depends_on:
            - mongo
        ports:
          - "8888:8081"
    server:
        depends_on:
            - mongo
        image: "gcr.io/$PROJECT_ID/taxeedee_db"
        ports:
            - "50051:50051"
