version: '3'

services:
    mongo:
        image: mongo
    mongo-express:
        image: mongo-express
        environment:
            - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
            - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
        depends_on:
            - mongo
        ports:
          - "8888:8081"
    server:
        depends_on:
            - mongo
        image: "gcr.io/$PROJECT_ID/taxeedee_db"
        ports:
            - "50051:50051"
