# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: taxeedee.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='taxeedee.proto',
  package='taxeedee',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0etaxeedee.proto\x12\x08taxeedee\x1a\x1fgoogle/protobuf/timestamp.proto\"5\n\x05Photo\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x10\n\x08safe_url\x18\x03 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\"$\n\x08Position\x12\x0b\n\x03lat\x18\x01 \x01(\x01\x12\x0b\n\x03lng\x18\x02 \x01(\x01\"O\n\x08Location\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x02 \x01(\t\x12$\n\x08position\x18\x03 \x01(\x0b\x32\x12.taxeedee.Position\"\x19\n\tParagraph\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x14\n\x05Video\x12\x0b\n\x03url\x18\x01 \x01(\t\"\x83\x01\n\x0b\x43ontentNode\x12 \n\x05photo\x18\x01 \x01(\x0b\x32\x0f.taxeedee.PhotoH\x00\x12 \n\x05video\x18\x02 \x01(\x0b\x32\x0f.taxeedee.VideoH\x00\x12(\n\tparagraph\x18\x03 \x01(\x0b\x32\x13.taxeedee.ParagraphH\x00\x42\x06\n\x04node\"/\n\x07\x43ontent\x12$\n\x05nodes\x18\x01 \x03(\x0b\x32\x15.taxeedee.ContentNode\"\xd6\x01\n\x04Post\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x1e\n\x05photo\x18\x04 \x01(\x0b\x32\x0f.taxeedee.Photo\x12-\n\ttimestamp\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12$\n\x08location\x18\x07 \x01(\x0b\x32\x12.taxeedee.Location\x12-\n\x12structured_content\x18\t \x01(\x0b\x32\x11.taxeedee.Contentb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_PHOTO = _descriptor.Descriptor(
  name='Photo',
  full_name='taxeedee.Photo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='taxeedee.Photo.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='safe_url', full_name='taxeedee.Photo.safe_url', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='taxeedee.Photo.title', index=2,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=114,
)


_POSITION = _descriptor.Descriptor(
  name='Position',
  full_name='taxeedee.Position',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lat', full_name='taxeedee.Position.lat', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lng', full_name='taxeedee.Position.lng', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=152,
)


_LOCATION = _descriptor.Descriptor(
  name='Location',
  full_name='taxeedee.Location',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='city', full_name='taxeedee.Location.city', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='country', full_name='taxeedee.Location.country', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position', full_name='taxeedee.Location.position', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=233,
)


_PARAGRAPH = _descriptor.Descriptor(
  name='Paragraph',
  full_name='taxeedee.Paragraph',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='taxeedee.Paragraph.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=260,
)


_VIDEO = _descriptor.Descriptor(
  name='Video',
  full_name='taxeedee.Video',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='taxeedee.Video.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=262,
  serialized_end=282,
)


_CONTENTNODE = _descriptor.Descriptor(
  name='ContentNode',
  full_name='taxeedee.ContentNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='photo', full_name='taxeedee.ContentNode.photo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='video', full_name='taxeedee.ContentNode.video', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='paragraph', full_name='taxeedee.ContentNode.paragraph', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='node', full_name='taxeedee.ContentNode.node',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=285,
  serialized_end=416,
)


_CONTENT = _descriptor.Descriptor(
  name='Content',
  full_name='taxeedee.Content',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodes', full_name='taxeedee.Content.nodes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=418,
  serialized_end=465,
)


_POST = _descriptor.Descriptor(
  name='Post',
  full_name='taxeedee.Post',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='taxeedee.Post.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='taxeedee.Post.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='taxeedee.Post.content', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='photo', full_name='taxeedee.Post.photo', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='taxeedee.Post.timestamp', index=4,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location', full_name='taxeedee.Post.location', index=5,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='structured_content', full_name='taxeedee.Post.structured_content', index=6,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=468,
  serialized_end=682,
)

_LOCATION.fields_by_name['position'].message_type = _POSITION
_CONTENTNODE.fields_by_name['photo'].message_type = _PHOTO
_CONTENTNODE.fields_by_name['video'].message_type = _VIDEO
_CONTENTNODE.fields_by_name['paragraph'].message_type = _PARAGRAPH
_CONTENTNODE.oneofs_by_name['node'].fields.append(
  _CONTENTNODE.fields_by_name['photo'])
_CONTENTNODE.fields_by_name['photo'].containing_oneof = _CONTENTNODE.oneofs_by_name['node']
_CONTENTNODE.oneofs_by_name['node'].fields.append(
  _CONTENTNODE.fields_by_name['video'])
_CONTENTNODE.fields_by_name['video'].containing_oneof = _CONTENTNODE.oneofs_by_name['node']
_CONTENTNODE.oneofs_by_name['node'].fields.append(
  _CONTENTNODE.fields_by_name['paragraph'])
_CONTENTNODE.fields_by_name['paragraph'].containing_oneof = _CONTENTNODE.oneofs_by_name['node']
_CONTENT.fields_by_name['nodes'].message_type = _CONTENTNODE
_POST.fields_by_name['photo'].message_type = _PHOTO
_POST.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_POST.fields_by_name['location'].message_type = _LOCATION
_POST.fields_by_name['structured_content'].message_type = _CONTENT
DESCRIPTOR.message_types_by_name['Photo'] = _PHOTO
DESCRIPTOR.message_types_by_name['Position'] = _POSITION
DESCRIPTOR.message_types_by_name['Location'] = _LOCATION
DESCRIPTOR.message_types_by_name['Paragraph'] = _PARAGRAPH
DESCRIPTOR.message_types_by_name['Video'] = _VIDEO
DESCRIPTOR.message_types_by_name['ContentNode'] = _CONTENTNODE
DESCRIPTOR.message_types_by_name['Content'] = _CONTENT
DESCRIPTOR.message_types_by_name['Post'] = _POST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Photo = _reflection.GeneratedProtocolMessageType('Photo', (_message.Message,), dict(
  DESCRIPTOR = _PHOTO,
  __module__ = 'taxeedee_pb2'
  # @@protoc_insertion_point(class_scope:taxeedee.Photo)
  ))
_sym_db.RegisterMessage(Photo)

Position = _reflection.GeneratedProtocolMessageType('Position', (_message.Message,), dict(
  DESCRIPTOR = _POSITION,
  __module__ = 'taxeedee_pb2'
  # @@protoc_insertion_point(class_scope:taxeedee.Position)
  ))
_sym_db.RegisterMessage(Position)

Location = _reflection.GeneratedProtocolMessageType('Location', (_message.Message,), dict(
  DESCRIPTOR = _LOCATION,
  __module__ = 'taxeedee_pb2'
  # @@protoc_insertion_point(class_scope:taxeedee.Location)
  ))
_sym_db.RegisterMessage(Location)

Paragraph = _reflection.GeneratedProtocolMessageType('Paragraph', (_message.Message,), dict(
  DESCRIPTOR = _PARAGRAPH,
  __module__ = 'taxeedee_pb2'
  # @@protoc_insertion_point(class_scope:taxeedee.Paragraph)
  ))
_sym_db.RegisterMessage(Paragraph)

Video = _reflection.GeneratedProtocolMessageType('Video', (_message.Message,), dict(
  DESCRIPTOR = _VIDEO,
  __module__ = 'taxeedee_pb2'
  # @@protoc_insertion_point(class_scope:taxeedee.Video)
  ))
_sym_db.RegisterMessage(Video)

ContentNode = _reflection.GeneratedProtocolMessageType('ContentNode', (_message.Message,), dict(
  DESCRIPTOR = _CONTENTNODE,
  __module__ = 'taxeedee_pb2'
  # @@protoc_insertion_point(class_scope:taxeedee.ContentNode)
  ))
_sym_db.RegisterMessage(ContentNode)

Content = _reflection.GeneratedProtocolMessageType('Content', (_message.Message,), dict(
  DESCRIPTOR = _CONTENT,
  __module__ = 'taxeedee_pb2'
  # @@protoc_insertion_point(class_scope:taxeedee.Content)
  ))
_sym_db.RegisterMessage(Content)

Post = _reflection.GeneratedProtocolMessageType('Post', (_message.Message,), dict(
  DESCRIPTOR = _POST,
  __module__ = 'taxeedee_pb2'
  # @@protoc_insertion_point(class_scope:taxeedee.Post)
  ))
_sym_db.RegisterMessage(Post)


# @@protoc_insertion_point(module_scope)
